replicas: 4
selector:
  matchLabels:
    app: sample-app
template:
  metadata:
    labels:
      app: sample-app
      team: platform
    annotations:
      owner: Abdelhameed Nael     
  spec:
    containers:
      - name: sample-app
        image: nginx:1.27
        ports:
          - containerPort: 8080

        readinessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 10

        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 250m
            memory: 256Mi

        env:
          - name: APP_ENV
            value: "production"
          - name: LOG_LEVEL
            value: "info"

