apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app-deployment
spec:
  template:
    spec:
      containers:
        - name: my-app-container
          image: my-app-image:v1.2.0
          ports:
            - containerPort: 80