apiVersion: v1
kind: Service
metadata:
  name: sample-app-svc
  labels:
    app: sample-app
    team: platform
  annotations:    
    owner: Abdelhameed Nael 
spec:
  type: ClusterIP
  selector:
    app: sample-app
  ports:
    - port: 80
      targetPort: 8080
